Repository kinopio-club/kinopio-client, pull requests merged in 2025-04, with the labels that each got.

#604 currentBoxes port z-index methods from currentCards
  src/components/Box.vue
  src/store/currentBoxes.js
  src/store/currentCards.js
Labels: Awaiting Assignee Response

#609 Add default og:image
  index.html
  src/pageMeta.js
  vite.config.js
Labels: Ready to Merge, Current Priority

#610 Add Netlify edge functions to add correct space Open Graph meta tags
  .cert/cert.pem
  .cert/key.pem
  README.md
  index.html
  netlify.toml
  netlify/edge-functions/page-meta.js
  netlify/edge-functions/utils/rewriteIndexHtml.js
  src/cache.js
  src/components/BackgroundPreview.vue
  src/components/Notifications.vue
  src/components/WindowHistoryHandler.vue
  src/components/dialogs/SignUpOrIn.vue
  src/components/layers/PaintSelectCanvas.vue
  src/pageMeta.js
  src/router.js
  src/store/api.js
  src/store/currentSpace.js
  src/store/currentUser.js
  src/utils.js
  src/views/Add.vue
  vite.config.js
Labels: Ready to Merge
